wordpressUsername: yuval
## @param wordpressPassword WordPress user password
## Defaults to a random 10-character alphanumeric string if not set
##
wordpressPassword: mypass

resources:
  limits:
    memory: 1024Mi
    cpu: 500m
  requests:
    memory: 512Mi
    cpu: 250m
