apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Get the logs from the containers running in the cluster
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
      tag wordpress.log
      <parse>
        @type regexp
        expression /^(?<timestamp>.+) (?<stream>stdout|stderr) [^ ]* (?<host>[^ ]*) - - \[(?<time>[^\]]*)\] "(?<method>[A-Z]+) (?<path>[^"]*) HTTP\/1\.[01]" (?<code>\d+) (?<size>\d+)$/
        time_format %d/%b/%Y:%H:%M:%S %z
      </parse>
    </source>

    # Send the logs to elasticsearch
    <match **>
      @type elasticsearch
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      logstash_format true
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
